### ISSUE TITLE
Malformed response - response 6

### ISSUE THREAD

**Issue by mastersuv** [MichaelBelgium/MV_Youtube#10]
Hi there Michael,
I'm trying to implement this in my local server, just for testing purposes, and by the way, I'm also using your server at _michaelbelgium.me/ytconverter/_

Everything is ready and running but the songs are not playing in game, it says there was a problem downloading the song: malformed response - response 6.

I looked up into the Downloads folder on your server, and the Youtube URLs I tested were, in fact, downloaded, but never played. (You can find them here: http://michaelbelgium.me/ytconverter/download/)

Do you happen to know what is going on in my case? Thank you in advance.

**Comment by mastersuv** [comment]
I'm guessing, it has something to do with the Json Parser

**Comment by MichaelBelgium** [comment]
As you're using the default stuff, you didn't edit anything in the include right?

**Comment by mastersuv** [comment]
That's correct

**Comment by MichaelBelgium** [comment]
Thats strange then ... 🤔

**Comment by mastersuv** [comment]
Just for the record:
Still can't find a solution for this, but I learned some things.

The problem is not SAMPSON or Json Parser. It seems to be something wrong with a_http.inc when the HTTP GET, for example, when using /search [query] we are calling this function on `[MV]_Youtube.inc`

`stock SearchYoutubeVideos(playerid, searchquery[])
{
	new requestlink[128];
	format(requestlink, sizeof(requestlink), "%s/search.php?q=%s&max_results=%i", CONVERTER_PATH, searchquery, MAX_SEARCH_RESULTS);
	**HTTP(playerid, HTTP_GET, requestlink, "", "OnSearchResponse");**
}`

On the HTTP line (marked with bold text) we are making the HTTP GET Request, and the response is taken to the `OnSearchResponse` callback. For the /search command to work, the response result must be 200(OK), but instead I'm receiving `malformed response - response 6`.

That error message is being taken from `a_http.inc` include here:

` /*  SA-MP threaded HTTP/1.0 client for pawn
 *
 *  (c) Copyright 2010, SA-MP Team
 *
 */

// HTTP requests
#define HTTP_GET						1
#define HTTP_POST						2
#define HTTP_HEAD						3

// HTTP error response codes
// These codes compliment ordinary HTTP response codes returned in 'response_code'
// (10x) (20x OK) (30x Moved) (40x Unauthorised) (50x Server Error)  
#define HTTP_ERROR_BAD_HOST				1
#define HTTP_ERROR_NO_SOCKET			2
#define HTTP_ERROR_CANT_CONNECT			3
#define HTTP_ERROR_CANT_WRITE			4
#define HTTP_ERROR_CONTENT_TOO_BIG		5
#define HTTP_ERROR_MALFORMED_RESPONSE	6

native HTTP(index, type, url[], data[], callback[]);

// example HTTP callback: public MyHttpResponse(index, response_code, data[]) { ... }`

**Comment by MichaelBelgium** [comment]
Yes its thrown by the HTTP function. As ure trying locally, did u try to do it via the browser?

**Comment by mastersuv** [comment]
On browser seems to be working fine.
I'm starting to believe that the issue is caused by yourserver, probably the response headers.

I tried on my vps and it's working now.

**Comment by mastersuv** [comment]
My apologies... Now I get what you meant when you say I was trying locally.
Is working with your server too. Sorry.
