### ISSUE TITLE
Is the michaelbelgium domain still functional?

### ISSUE THREAD

**Issue by ReshiramZekrom1** [MichaelBelgium/MV_Youtube#12]
Since few weeks the script is giving me many problems while downloading files never downloaded before. No streams are generated and kinda everything is returning "undefined". :(

Is it everything okay or did I do anything wrong pawn-side?

**Comment by MichaelBelgium** [comment]
The domain itself is still functional but after checking the api it does give a wrong reponse. I'll look into it

**Comment by MichaelBelgium** [comment]
Fixed
