### ISSUE TITLE
Converting videos broken (most videos don't work)

### ISSUE THREAD

**Issue by TokicMajstor** [MichaelBelgium/MV_Youtube#14]
Every time I try to convert a video (manually of trough the include) I get this error:

`The command "'/usr/local/bin/youtube-dl' 'https://www.youtube.com/watch?v=Vqp0bLulp5g' '--no-playlist' '--ignore-config' '--write-info-json' '--skip-download'" failed. Exit Code: 1(General error) Working directory: download/ Output: ================ [youtube] Vqp0bLulp5g: Downloading webpage [youtube] Downloading just video Vqp0bLulp5g because of --no-playlist [youtube] Vqp0bLulp5g: Downloading js player f82a8c37 Error Output: ================ WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this. ERROR: Signature extraction failed: Traceback (most recent call last): File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1420, in _decrypt_signature video_id, player_url, s File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1332, in _extract_signature_function cache_res = res(test_string) File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1396, in <lambda> return lambda s: initial_function([s]) File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf res, abort = self.interpret_statement(stmt, local_vars) File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement v = self.interpret_expression(expr, local_vars, allow_recursion) File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression m.group('expr'), local_vars, allow_recursion - 1) File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression m.group('x'), local_vars, allow_recursion - 1) File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement v = self.interpret_expression(expr, local_vars, allow_recursion) File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression raise ExtractorError('Unsupported JS expression %r' % expr) ExtractorError: Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by ExtractorError(u"Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. `

Searching videos is working just fine, but converting isn't. Also some older videos work, while all the never ones don't work (I just realized that it doesn't actually matter how old is video but it happens very often that the older ones work).

**Comment by MichaelBelgium** [comment]
I updated youtube-dl, try again? When using the api directly it can convert the video

**Comment by TokicMajstor** [comment]
It is all working now, thank you
