### ISSUE TITLE
pawn-requests support

### ISSUE THREAD

**Issue by MichaelBelgium** [MichaelBelgium/MV_Youtube#17]
Make the include support ONLY [pawn-requests](https://github.com/Southclaws/pawn-requests)

* No more need for SAMPSON plugin
* Eliminates the usage of the badly, dinosaur function `HTTP` which doesn't even support https requests (if i remember) and auth headers and POST body and so on

**Comment by MeIsAlan** [comment]
It would be pretty good if SAMPSON is no longer required.
