### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by marcelog09** [MichaelBelgium/MV_Youtube#19]
When trying to play a song using the PlayYoutubeVideoFor function, i get the following error in:

![image](https://user-images.githubusercontent.com/55034630/183263634-5961832b-dab9-4571-91a7-2f462bff6dbd.png)

**Comment by MichaelBelgium** [comment]
Looking into it. Some problem with http requests to Laravel

**Comment by MichaelBelgium** [comment]
Was a web server issue. Fixed
