### ISSUE TITLE
I have a problem with my api key

### ISSUE THREAD

**Issue by PhucDiamond-VN** [MichaelBelgium/MV_Youtube#22]
![image](https://github.com/MichaelBelgium/MV_Youtube/assets/160996471/520bcd36-876b-4995-a135-1601d0f75c89)
![image](https://github.com/MichaelBelgium/MV_Youtube/assets/160996471/5be95dde-b273-42c5-8400-e363307a3bd8)
![image](https://github.com/MichaelBelgium/MV_Youtube/assets/160996471/903f0ecd-adc5-4d01-b11e-8076949fca32)

Did I do something wrong?, please help me

**Comment by MichaelBelgium** [comment]
If you're using youtube.michaelbelgium.me you don't need to create your own (google) api keys.

You can login/register on youtube.michaelbelgium.me and create a token on the dashboard, and use that token in the include on this line

https://github.com/MichaelBelgium/MV_Youtube/blob/3df169239ea4bf3ea15e9b161a2eb26df2805ba0/MV_Youtube.inc#L22

**Comment by MichaelBelgium** [comment]
Actually, youtube.michaelbelgium.me did move to another server and does not support HTTP requests anymore, only HTTPS.

It might be broken for samp servers. #17 would be the fix but someone need to volunteer to do the change. 

I do not play SAMP anymore, neither code PAWN anymore.

**Comment by PhucDiamond-VN** [comment]
> Trên thực tế, youtube.michaelbelgium.me đã chuyển sang máy chủ khác và không hỗ trợ các yêu cầu HTTP nữa, chỉ hỗ trợ HTTPS.
> 
> Nó có thể bị hỏng đối với các máy chủ samp. #17 sẽ là giải pháp nhưng cần có ai đó tình nguyện thực hiện thay đổi.
> 
> Mình không chơi SAMP nữa, cũng không code PAWN nữa. Nếu bạn đang bất hòa về samp/open-mp, bạn có thể hỏi ở đó

Thank you for your time
